### ISSUE TITLE
taup: taup_setsac can not accept a directory name

### ISSUE THREAD

**Issue by core-man** [seismo-learn/software#101]
This fixed in https://github.com/crotwell/TauP/issues/13

**Comment by seisman** [comment]
The issue was fixed in TauP 2.5.0. 

I don't mention this feature in the taup_setsac tutorial, because I feel it's better to use explicitly specify SAC file names, i.e., `taup setsac ... directory/*.SAC`, rather than `taup setsac ... directory/`.
