### ISSUE TITLE
Consistent installation path for all software

### ISSUE THREAD

**Issue by seisman** [seismo-learn/software#108]
The software may be categorized into the following groups based on the way they're installed:

1. software installed by package managers (apt-get, dnf, conda), e.g., obspy: these software are installed to the default path, and we don't need to care about it.
2. Software that can be used without compilation, e.g., TauP, and SOD: put them in the "~/src" or `/opt` or `~/local`?
3. Software that need compilation, but no need to install, so the source and binary files are in the same directory, e.g., fk: put them in the `~/src` directory?
4. Software that need compilation, but no need to install, and the source and binary files are in bin and src directory, respectively, e.g., CPS: put them in the "~/src" directory?
5. Software that need compilation, and need to install, e.g., GMT: put them in `/opt`, `~/local`?
6. Small utilities, with a single binary file, e.g., `distaz`: put them in `~/bin`?

So, software is usually installed into the following paths:

- `/opt/XXX`
- `~/local/XXX`
- `~/src/XXX`
- `~/bin/`

What's the installation path we should recommend? We may need to document it in the appendix of https://github.com/seismo-learn/seismology101.

Related to:

- https://blog.seisman.info/how-to-install-softwares-under-centos-7
- https://blog.seisman.info/file-organization/

More notes:

1. The above groups are based on my quick thoughts and may don't make sense.
2. **Linux**: some closed-source software like matlab, mendeley, intel compiler, usually have the default installation path to `/opt`
3. **macOS**: Homebrew defaults to `/usr/local`
4. **macOS**: macports, (package manager similar to homebrew), defaults to `/opt/local`
5. **On Linux servers,** we usually don't have root permissions, so we have to install software in the home directory.

**Comment by seisman** [comment]
Here is what I propose:

1. Save all software tarballs (e.g., `TauP-2.3.4.tgz`) in the `~/software` directory
2. All source codes are in the `~/src` directory
3. If no `make install` is needed (e.g., fk, cps), then we need to add `~/src/XXX` or `~/src/XXX/bin` to PATH
4. If `make install` is needed (e.g., GMT), then we install it to `~/local/XXX`, and add `~/local/XXX/bin` to PATH
5. for small utilities, similar to the above point 3, but we copy the executable to `~/bin/`

Is it reasonable or too complicated?

**Comment by core-man** [comment]
> 1. Save all software tarballs (e.g., `TauP-2.3.4.tgz`) in the `~/software` directory

Yes.

> 2. All source codes are in the `~/src` directory

Yes.

> 3. If no `make install` is needed (e.g., fk, cps), then we need to add `~/src/XXX` or `~/src/XXX/bin` to PATH

Yes.

> 5. for small utilities, similar to the above point 3, but we copy the executable to `~/bin/`

Yes, otherwise, we may have a dirty `.zshrc`.

> 4. If `make install` is needed (e.g., GMT), then we install it to `~/local/XXX`, and add `~/local/XXX/bin` to PATH

Why not `opt`? Or Why the default install path is `opt` for some software like MatLab.

We may decide how to use `/opt` and `~/local`.

-------
> Software that can be used without compilation, e.g., TauP, and SOD: put them in the "~/src" or /opt or ~/local?

Better not `~/src` since the tarballs are already stored in `~/software`.

Whether `/opt` or `~/local`?

--------
> So, software is usually installed into the following paths:
> - `/opt/XXX`
> - `~/local/XXX`
> - `~/src/XXX`
> - `~/bin/`

Just as the above, the software installed in `~/src/` and `~/bin` is okay now.
We may decide how to install software in `/opt` or `~/local`.

**Comment by core-man** [comment]
**Here is a simple summary:**

1. Software that can be used without compilation

  - put them in the `/opt` or `~/local`, e.g., `TauP` and `SOD`.

2. Software that need compilation, but no need to install.

  - usually put them in the `~/src`, e.g., `fk`.
  - for small utilities with a single binary file, put them in `~/bin`, e.g., `distaz`.

3. Software that need compilation, and need to install

  - put them in `/opt` or `~/local`, e.g., `GMT`
  - How about `matlab`, `mendeley`, `intel compiler`


Install paths:

- [x] `~/src/`
- [x] `~/bin/`
- [x] `/opt`
- [x] `~/local/`

**Comment by seisman** [comment]
> > 1. If `make install` is needed (e.g., GMT), then we install it to `~/local/XXX`, and add `~/local/XXX/bin` to PATH
> 
> Why not `opt`? Or Why the default install path is `opt` for some software like MatLab.
> 
> We may decide how to use `/opt` and `~/local`.

`opt` means optional. I don't know why closed-source software defaults to `/opt`, but that's very common (Google Chrome and Google Earth also defaults to `/opt`).

The reasons I prefer to `~/local` are:

- Seismological software are different from that closed-source or commercial software, so it's better to put them in different directories.
- Keep the same directory structure for personal computer and Linux server, as we can't install software to `/opt` on Linux servers.

> > Software that can be used without compilation, e.g., TauP, and SOD: put them in the "~/src" or /opt or ~/local?
> 
> Better not `~/src` since the tarballs are already stored in `~/software`.
> 
> Whether `/opt` or `~/local`?

I'm OK with putting them in `/opt` or `~/local`, as they're not "source codes".

**Comment by core-man** [comment]
I prefer to put seismological codes that need to be installed in `~/local`.
Now the question is which software shall we put in `/opt`.

**Comment by core-man** [comment]
> 1. Software that can be used without compilation
> 
> * put them in the `~/local`, e.g., `TauP` and `SOD`.

@seisman How about putting them in `~/local/bin/`.

**Comment by seisman** [comment]
> > 1. Software that can be used without compilation
> > 
> > 
> > * put them in the `~/local`, e.g., `TauP` and `SOD`.
> 
> @seisman How about putting them in `~/local/bin/`.

Do you mean copying executables like `taup_time` to `~/local/bin`?

**Comment by core-man** [comment]
> > > 1. Software that can be used without compilation
> > > 
> > > 
> > > * put them in the `~/local`, e.g., `TauP` and `SOD`.
> > 
> > 
> > @seisman How about putting them in `~/local/bin/`.
> 
> Do you mean copying executables like `taup_time` to `~/local/bin`?

Yes. If we use `~/local`, we may better not use `~bin`. It is more clearer

**Comment by seisman** [comment]
> > > > 1. Software that can be used without compilation
> > > > 
> > > > 
> > > > * put them in the `~/local`, e.g., `TauP` and `SOD`.
> > > 
> > > 
> > > @seisman How about putting them in `~/local/bin/`.
> > 
> > 
> > Do you mean copying executables like `taup_time` to `~/local/bin`?
> 
> Not really. I mean some utilities like `distaz`.

Some Linux distros (maybe CentOS) already have a `${HOME}/bin` directory. If we choose `~/local/bin`, it means `~/bin` is always empty.

**Comment by seisman** [comment]
BTW, there is a `~/.local/` directory. I'm a little afraid that users may be confused about `~/.local` and `~/local`, although the former one is hidden by default.

**Comment by core-man** [comment]
> > > > > 1. Software that can be used without compilation
> > > > > 
> > > > > 
> > > > > * put them in the `~/local`, e.g., `TauP` and `SOD`.
> > > > 
> > > > 
> > > > @seisman How about putting them in `~/local/bin/`.
> > > 
> > > 
> > > Do you mean copying executables like `taup_time` to `~/local/bin`?
> > 
> > 
> > Not really. I mean some utilities like `distaz`.
> 
> Some Linux distros (maybe CentOS) already have a `${HOME}/bin` directory. If we choose `~/local/bin`, it means `~/bin` is always empty.

I think it does not matter. The reason we create `~/bin` or `~/local` is just to put executive files. Their source codes are in `~/src`. I think `distaz` and `GMT` are the same.

**Comment by core-man** [comment]
> ormer on

We'd better have another name, like `~/src` and `~/software` are good names.

**Comment by seisman** [comment]
> I think it does not matter. The reason we create `~/bin` or `~/local` is just to put executive files. Their source codes are in `~/src`. 

`~/bin` is one of the commonly used directory to store executables and simple scripts. I don't think we should break the rules, by forcing executables (e.g., `distaz`) and scripts to `~/local/bin`.

**Comment by core-man** [comment]
> > I think it does not matter. The reason we create `~/bin` or `~/local` is just to put executive files. Their source codes are in `~/src`.
> 
> `~/bin` is one of the commonly used directory to store executables and simple scripts. I don't think we should break the rules, by forcing executables (e.g., `distaz`) and scripts to `~/local/bin`.

Okay.

**Comment by core-man** [comment]
> BTW, there is a `~/.local/` directory. I'm a little afraid that users may be confused about `~/.local` and `~/local`, although the former one is hidden by default.

How about `~/opt`?

**Comment by seisman** [comment]
> How about `~/opt`?

Yes, that's exactly the one I'm going to say. As closed-source software prefer to `/opt/XXX`, it seems intuitive to have open-source/seismological software in `~/opt/XXX`.

**Comment by core-man** [comment]
> > How about `~/opt`?
> 
> Yes, that's exactly the one I'm going to say. As closed-source software prefer to `/opt/XXX`, it seems intuitive to have open-source/seismological software in `~/opt/XXX`.

Great.

**Comment by core-man** [comment]
**A simple summary:**

1. Source codes

 - Save all software tarballs in the `~/software`, e.g., `TauP-2.3.4.tgz`, `fk.tar.gz`.
 - Put source codes of all software that need compilation in the `~/src`, e.g., `fk`, `distaz`, `GMT`.

2. Software that can be used without compilation

  - put them in the `~/opt/`, e.g., `TauP` and `SOD`.

3. Software that need compilation, but no need to install.

  - usually put them in the `~/src`, e.g., `fk`.
  - for small utilities with a single binary file, move the executive file in `~/bin`, e.g., `distaz`.

4. Software that need compilation, and need to install

  - put them in `~/opt`, e.g., `GMT`
 
5. Closed-source or commercial software
  - install them in `/opt`, e.g., `matlab`, `mendeley`, `intel compiler`.


Install paths:

- [x] `~/src/`
- [x] `~/bin/`
- [x] `~/opt/`
- [x] `/opt`

**Comment by seisman** [comment]
> The one I can remember is what's the path for our own codes and sripts. How about `~/codes/` and `~/scripts/` ?

I think that's a separate question, and I don't want to discuss it in this issue, as it's off-topic.

**Comment by seisman** [comment]
My other concern is, if I'm using a Linux server which I don't have root privilege, so I can't install packages to the system path. If fftw is missing, then I have to build fftw from source and install it in my home directory. Then I have two options:

1. Install fftw to `~/opt/fftw`, i.e., executables in `~/opt/fftw/bin`, libraries in `~/opt/fftw/lib`, and header files in `~/opt/fftw/include`. To link to fftw, I think I have to add `~/opt/fftw/bin` to PATH, add `~/opt/fftw/lib` to LD_LIBRARY_PATH, and specify `~/opt/fftw/include` in ``-I``. For other packages, I need to do the same thing.
2. Install fftw to `~/usr/`, i.e., executables in `~/usr/bin`, libraries in `~/usr/lib`, and header files in `~/usr/include`. For all packages, I only need to add the paths once. 

It seems option 2 is better, right?

**Comment by seisman** [comment]
The only problem with option 2 is that, it may be a little difficult to uninstall a package if all software are writing to `~/usr/bin`, `~/usr/lib` and `~/usr/include`.

**Comment by core-man** [comment]
> My other concern is, if I'm using a Linux server which I don't have root privilege, so I can't install packages to the system path. If fftw is missing, then I have to build fftw from source and install it in my home directory. Then I have two options:
> 
> 1. Install fftw to `~/opt/fftw`, i.e., executables in `~/opt/fftw/bin`, libraries in `~/opt/fftw/lib`, and header files in `~/opt/fftw/include`. To link to fftw, I think I have to add `~/opt/fftw/bin` to PATH, add `~/opt/fftw/lib` to LD_LIBRARY_PATH, and specify `~/opt/fftw/include` in `-I`. For other packages, I need to do the same thing.
> 2. Install fftw to `~/usr/`, i.e., executables in `~/usr/bin`, libraries in `~/usr/lib`, and header files in `~/usr/include`. For all packages, I only need to add the paths once.
> 
> It seems option 2 is better, right?

I would like to choose option 1 for two reasons.

1. I think usually we only need to install a few dependent software or libraries. It really does not matter to add bin, lib, or include several times.
2. It is not easy to manage each package.

**Comment by seisman** [comment]
> > My other concern is, if I'm using a Linux server which I don't have root privilege, so I can't install packages to the system path. If fftw is missing, then I have to build fftw from source and install it in my home directory. Then I have two options:
> > 
> > 1. Install fftw to `~/opt/fftw`, i.e., executables in `~/opt/fftw/bin`, libraries in `~/opt/fftw/lib`, and header files in `~/opt/fftw/include`. To link to fftw, I think I have to add `~/opt/fftw/bin` to PATH, add `~/opt/fftw/lib` to LD_LIBRARY_PATH, and specify `~/opt/fftw/include` in `-I`. For other packages, I need to do the same thing.
> > 2. Install fftw to `~/usr/`, i.e., executables in `~/usr/bin`, libraries in `~/usr/lib`, and header files in `~/usr/include`. For all packages, I only need to add the paths once.
> > 
> > It seems option 2 is better, right?
> 
> I would like to choose option 1 for two reasons.
> 
> 1. I think usually we only need to install a few dependent software or libraries. It really does not matter to add bin, lib, or include several times.
> 2. It is not easy to manage each package.

That really depends on the Linux server you're using. If you want to install GMT on a Linux server, which doesn't have netcdf and gdal installed, then you have to build more than 10 packages from source codes. That's crazy!

Never mind. I believe we don't have to worry about until someone uses those ridiculous servers.

**Comment by seisman** [comment]
> That really depends on the Linux server you're using. If you want to install GMT on a Linux server, which doesn't have netcdf and gdal installed, then you have to build more than 10 packages from source codes. That's crazy!

Oops, I just realized it's better to use [vcpkg](https://github.com/microsoft/vcpkg) for these rare cases.

**Comment by core-man** [comment]
> > That really depends on the Linux server you're using. If you want to install GMT on a Linux server, which doesn't have netcdf and gdal installed, then you have to build more than 10 packages from source codes. That's crazy!
> 
> Oops, I just realized it's better to use [vcpkg](https://github.com/microsoft/vcpkg) for these rare cases.

Seem great.

**Comment by seisman** [comment]
I think we both agree with https://github.com/seismo-learn/software/issues/108#issuecomment-758429853, and we should document it in https://github.com/seismo-learn/seismology101 appendix, and update the installation paths of TauP, SOD et al.

**Comment by core-man** [comment]
> I think we both agree with [#108 (comment)](https://github.com/seismo-learn/software/issues/108#issuecomment-758429853), and we should document it in https://github.com/seismo-learn/seismology101 appendix, and update the installation paths of TauP, SOD et al., right?

Yes.

**Comment by seisman** [comment]
OK, I will submit a draft PR in a few minutes.

**Comment by core-man** [comment]
Fixed by https://github.com/seismo-learn/seismology101/pull/41. So closed.
