### ISSUE TITLE
Add CI jobs to test the installation

### ISSUE THREAD

**Issue by seisman** [seismo-learn/software#135]
We already provide install instructions for some software, and we test them under both Linux and macOS. However, there is no guarantee that the installations are correct when new versions are released.

Perhaps we can add CI jobs (runs weekly or monthly) installing these software and run simple tests so that we know they are all correctly installed?

**Comment by core-man** [comment]
can ci work on macos, linux and windows?

**Comment by seisman** [comment]
Yes, but we may only want to test on Linux and macos

**Comment by core-man** [comment]
sound good

**Comment by seisman** [comment]
Environment:

- [ ] anaconda
- [ ] java

Software to test:

- [ ] cps
- [ ] fk
- [ ] gcap3d
- [ ] obspy
- [ ] sod
- [ ] taup
- [ ] distaz

Software without tests:

- [ ] gmt
- [ ] hinetpy
- [ ] sac
- [ ] saclst
