### ISSUE TITLE
Add a general note for all installation instructions

### ISSUE THREAD

**Issue by seisman** [seismo-learn/software#146]
I can see two issues with our current install instructions:

1. `gcc` and `gfortran` may not be installed 
2. users may use zsh, not bash, but all the instructions make changes to `~/.bahsrc`

What we can do is add a note at the top of the installation sections:

1. The install instructions assume that you already have developing software (gcc, gfortran, make, git) installed, following the setup guide.
2. Explain that if users are using zsh, they should make change to `~/.zshrc` instead.

**Comment by core-man** [comment]
That's also what I'm concerned.
You mean at the landing page?

**Comment by seisman** [comment]
> That's also what I'm concerned.
> You mean at the landing page?

No. I mean at the top of the installation pages, e.g., https://seismo-learn.org/software/fk/install/.

**Comment by seisman** [comment]
> We may first revise the template.

We don't have an "install" section in the template.

**Comment by core-man** [comment]
Could we add one?
