### ISSUE TITLE
Separate metadata (authors and last updated date) for each section

### ISSUE THREAD

**Issue by seisman** [seismo-learn/software#161]
Take this https://seismo-learn.org/software/taup/ as an example.

We now list the authors and last updated data on the TauP landing page. However, the TauP tutorials contain may sections and each section may be written by different authors and updated on different dates.

I think we should list the metadata on each section, instead of on the landing page.

- [x] CPS
- [x] fk
- [x] gCAP3D
- [x] ObsPy
- [x] SOD
- [x] TauP
- [x] Template

**Comment by core-man** [comment]
That's also what I am concerned.

**Comment by core-man** [comment]
You mean we keep software metadata on the landing page, while put tutorial authors and updating dates in each tutorial?

This is on landing page?
![Screenshot from 2021-02-02 12-43-11](https://user-images.githubusercontent.com/50591376/106553457-64ef6180-6554-11eb-87f1-6fb690254545.png)

This is on each tutorial?
![Screenshot from 2021-02-02 12-43-27](https://user-images.githubusercontent.com/50591376/106553483-7173ba00-6554-11eb-9d27-3424b3136c49.png)

**Comment by seisman** [comment]
Yes.

**Comment by seisman** [comment]
> You mean we keep software metadata on the landing page, while put tutorial authors and updating dates in each tutorial?

Working on the issue in PR #164, but I prefer **NOT** to list the metadata on the landing page, as they seem useless to me.

**Comment by core-man** [comment]
> > You mean we keep software metadata on the landing page, while put tutorial authors and updating dates in each tutorial?
> 
> Working on the issue in PR #164, but I prefer **NOT** to list the metadata on the landing page, as they seem useless to me.

These information is a good outline.

**Comment by seisman** [comment]
Sorry, I don't get it.

**Comment by core-man** [comment]
> Sorry, I don't get it.

We may still keep some of the metadata, e.g., website

**Comment by seisman** [comment]
The metadata on the landing pages are good. What I meant is I prefer not to list the contributors and last updated date on the landing page, which were already removed in PR #164

**Comment by core-man** [comment]
> The metadata on the landing pages are good. What I meant is I prefer not to list the contributors and last updated date on the landing page, which were already removed in PR #164

I got it. I thought you want to remove metadata on landing page.

**Comment by seisman** [comment]
Of course not.

**Comment by core-man** [comment]
> > You mean we keep software metadata on the landing page, while put tutorial authors and updating dates in each tutorial?
> 
> Working on the issue in PR #164, but I prefer **NOT** to list the metadata on the landing page, as they seem useless to me.

The second sentence looks a little like you want to remove metadata.

**Comment by seisman** [comment]
I agree it's a little misleading.
