### ISSUE TITLE
Upgrade to TauP 2.5.0

### ISSUE THREAD

**Issue by seisman** [seismo-learn/software#182]
TauP 2.5.0 is just released. We need to update the tutorials to TauP 2.5.0.

https://github.com/crotwell/TauP/releases

- [x] Metadata page
- [x] Install
- [x] Introduction
- [x] taup curve
- [x] taup time
- [x] taup setsac
- [x] taup path
- [x] test scripts

**Comment by core-man** [comment]
New release of TauP is available, 2.5.0
now with LGPL.
http://www.seis.sc.edu/downloads/TauP/TauP-2.5.0.tgz

It is also available via homebrew for Macintosh with:
```
brew tap crotwell/crotwell
brew install taup
```

Several bug fixes and three new tools:
- taup velplot：generate a gmt script to plot a velocity model
- taup slowplot - similar, but plot slowness
- taup velmerge - merge a partial velocity model into a base model, for example to replace crust and upper mantle while keeping rest of the earth model
