### ISSUE TITLE
Add badges for all the GitHub Actions

### ISSUE THREAD

**Issue by core-man** [seismo-learn/software#189]
We have GitHub actions with two badges (deploy and tests) in README.md. Shall we add badges for the other three?

- check-links.yml
- deploy.yml
- labeler.yml
- preview-pr.yml
- tests.yml

**Comment by seisman** [comment]
I think others are not necessary.

preview-pr and labeler only work in PRs, we will know whether they pass.

check-links runs every week, and we will see a new issue if any links are broken.
