### ISSUE TITLE
Maybe it is not necessary to install distaz

### ISSUE THREAD

**Issue by wangliang1989** [seismo-learn/software#224]
I think everyone install gmt.
````bash
$ distaz 30 120 40 121          
10.010483 4.423269 184.996480
$ echo 121 40 | gmt mapproject -Af120/30 -G120/30+uk
121     40      4.40109229385   1113.96646031
$ echo 121 40 | gmt mapproject -Af120/30 -G120/30+ud
121     40      4.40109229385   10.0181297686
````

**Comment by seisman** [comment]
`distaz` is more widely used and is also easier to write than the GMT command.

**Comment by wangliang1989** [comment]
> `distaz` is more widely used and is also easier to write than the GMT command.

No, GMT more widely because everybody needs to draw

**Comment by seisman** [comment]
`distaz` is included in the software site, because it's useful, not because it's required.

**Comment by wangliang1989** [comment]
useful和required不是一个意思吗

**Comment by seisman** [comment]
这个网站列出的是地震学科研过程中的常用软件，而不是列出必须软件。

`distaz` 很有用，但并不是必须的。`distaz` 与 `gmt mapproject` 具有相同的功能，并不意味着需要把 `distaz` 从网站中删除。

**Comment by wangliang1989** [comment]
好吧
