### ISSUE TITLE
Template for tutorials

### ISSUE THREAD

**Issue by seisman** [seismo-learn/software#24]
While @core-man is working on the TauP tutorials at https://github.com/seismo-learn/software/pull/23, I think we should first design a template or some rules for all tutorials.

Here are some of my thoughts:

1. A tutorial usually contains the following sections: introduction, installation, usage (optional), and examples (optional)
1. All sections should be in a single file if it's short, or several smaller files if it's too long
2. In the introduction section: list basic metadata of the software, including author (also link to author homepage if available), latest version, release date/year, platform (if not available on all platforms), main language, homepage, github repository (if available), License (if available)
3. Show the names of the authors and contributors of the tutorial (give them more credits)
4. Add a note that the tutorial is only tested on macOS/Linux/Windows using version x.x.x 

Please let me know your thoughts.

We can also add a template ReST file so that we can copy the template when we start a new tutorial.

**Comment by core-man** [comment]
Yes, we should have a tutorial template. Maybe we could complete it after or during the first TauP tutorial so that we can have some experience before discussing the template.

Points 3-5 are okay to revise after the tutorial, while we can first discuss 1-2. What does short mean, 2 or 3 pages on the web browser? Shall we also have a hard limit, e.g., 4 or 5 pages on the web browser?

**Comment by seisman** [comment]
> What does short mean, 2 or 3 pages on the web browser? Shall we also have a hard limit, e.g., 4 or 5 pages on the web browser?

3 pages seem to be a reasonable threshold.

**Comment by core-man** [comment]
> 3 pages seem to be a reasonable threshold.

You mean a hard limit or just a suggested length?

**Comment by seisman** [comment]
> > 3 pages seem to be a reasonable threshold.
> 
> You mean a hard limit or just a suggested length?

It's just a suggested length. We may not want to split a tutorial into separate files only because its length is 3-and-a-half pages.

**Comment by core-man** [comment]
Close the issue? See we already finish #27
