### ISSUE TITLE
Tutorial authors

### ISSUE THREAD

**Issue by seisman** [seismo-learn/software#51]
Currently we have:
![image](https://user-images.githubusercontent.com/3974108/103395651-2e5d9b80-4afd-11eb-913e-deacd78df592.png)

Perhaps we should change it to:

![image](https://user-images.githubusercontent.com/3974108/103395668-4af9d380-4afd-11eb-895b-57964caf4832.png)

**Comment by core-man** [comment]
Yes, both authors and proofreaders are contributors.

Then, how about other contributors? For example, those who submit an issue, PR and discussion.

**Comment by seisman** [comment]
Perhaps only list those who submit PRs as "authors" or "proofreaders".

**Comment by core-man** [comment]
Okay. So we have two kinds of contributors now, "authors" and "proofreaders".

**Comment by seisman** [comment]
Maybe three roles:

- authors: who write all or some of the tutorials (we may have multiple authors)
- reviewers: who review the tutorials, make suggestions about the content
- proofreaders: who fixes some typos or errors in the tutorials (only those who make PRs are considered).
