### ISSUE TITLE
Add how to use Chinese or English punctuations

### ISSUE THREAD

**Issue by core-man** [seismo-learn/software#55]
I think we may have to choose whether use Chinese or English punctuations, e.g.,

- `:`
- `、` or `,`

**Comment by seisman** [comment]
It's better to use Chinese punctuations, but ReST syntax sometimes doesn't work well with them.

**Comment by core-man** [comment]
[#47 (comment)](https://github.com/seismo-learn/software/pull/47#discussion_r550741326)

https://github.com/sparanoid/chinese-copywriting-guidelines/blob/master/README.md#%E5%85%A8%E5%BD%A2%E6%A8%99%E9%BB%9E%E8%88%87%E5%85%B6%E4%BB%96%E5%AD%97%E7%AC%A6%E4%B9%8B%E9%96%93%E4%B8%8D%E5%8A%A0%E7%A9%BA%E6%A0%BC
