### ISSUE TITLE
Add tutorials for distaz

### ISSUE THREAD

**Issue by core-man** [seismo-learn/software#69]
https://blog.seisman.info/calculate-dist-az-baz/

**Comment by seisman** [comment]
Tried to add the tutorial in #94, but it seems we should first explain distance, azimuth and back-azimuth in seismology101 or seismology (see also https://github.com/seismo-learn/seismology/issues/13).

**Comment by core-man** [comment]
We may explain it in seismology101 at least (see https://github.com/seismo-learn/seismology101/issues/15)

**Comment by seisman** [comment]
Sounds a good idea.
