### ISSUE TITLE
GitHub labeling

### ISSUE THREAD

**Issue by seisman** [seismo-learn/software#72]
Labels help us organize PRs and issues. I'm thinking how can we improve the labeling.

Do we want to add labels like "taup", "fk", "cap"?

**Comment by core-man** [comment]
For software, it's used to use software name as a tag instead of a large cate.

**Comment by seisman** [comment]
Sorry, it's unclear to me what you meant.

**Comment by core-man** [comment]
Software name is like a tag, while the lables like "new soft" or "new tutorial" is like a category

**Comment by seisman** [comment]
Yes, so you agree that we can add labels like "taup", "fk"?

**Comment by core-man** [comment]
of course. we can even use `taup-base` to indicate metadata, intro, and install, while `taup-usage` to indicate usage and examples.

**Comment by seisman** [comment]
> we can even use `taup-base` to indicate metadata, intro, and install, while `taup-usage` to indicate usage and examples.

That's too complicated.

**Comment by core-man** [comment]
Okay, we can just move on and test if only using software name is okay.

**Comment by seisman** [comment]
https://github.com/actions/labeler This one looks useful.

**Comment by core-man** [comment]
Just what we need~

**Comment by seisman** [comment]
I can leave it to you if you're willing to implement it.

**Comment by core-man** [comment]
Okay, I can have a try to be familiar with github action.

**Comment by core-man** [comment]
How about issue labeler?

**Comment by seisman** [comment]
I don't think there is an easy way to autolabel issues.

**Comment by core-man** [comment]
so let's label issues the same way as PR manully?

**Comment by core-man** [comment]
by the same github action use the same color to label PRs, which I think is good because too many colors are a little noisy.

**Comment by seisman** [comment]
> so let's label issues the same way as PR manully?

Yes.



> by the way，github action use the same color to label PRs, which I think is good because too many colors are a little noisy.

OK to me.

**Comment by core-man** [comment]
Great~ I am okay now.
