### ISSUE TITLE
Add a tutorial for saclst

### ISSUE THREAD

**Issue by core-man** [seismo-learn/software#95]
Although saclst is included in SAC, we may put it in utilities since it is useful to check SAC headers.

**Comment by seisman** [comment]
Add a link to https://seisman.github.io/SAC_Docs_zh/tools/saclst/ or maintain a separate tutorial?

**Comment by core-man** [comment]
I think a metadata page with the link to your sac manual is enough.

**Comment by seisman** [comment]
> I think a metadata page with the link to your sac manual is enough.

The metadata page would be very short.

**Comment by core-man** [comment]
Yes, I think we may at least have a brief metadata page for all software before jumping to the referenced manual.
